<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "clockwork"
 *
 * Auto generated by Extension Builder 2021-09-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'TYPO3 Clockwork Integration',
    'description' => 'TYPO3 Adapter for Clockwork php dev tools https://underground.works/clockwork',
    'category' => 'plugin',
    'author' => 'Michael Münch',
    'author_email' => 'michael.muench@itanix.de',
    'state' => 'alpha',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.2',
    'constraints' => [
        'depends' => [
            'typo3' => '10.4.0-10.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
