services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: false

  Itanix\Clockwork\Middleware\ClockworkInitialization:
    autowire: true
    autoconfigure: true

  Itanix\Clockwork\EventDispatcher\EventDispatcher:
    autowire: true
    public: true

  Itanix\Clockwork\EventListener\AssetRenderer\InjectAssets:
    tags:
      - name: event.listener
        identifier: itanix/clockwork/InjectAssets
        event: TYPO3\CMS\Core\Page\Event\BeforeJavaScriptsRenderingEvent

  Psr\EventDispatcher\EventDispatcherInterface:
    alias: Itanix\Clockwork\EventDispatcher\EventDispatcher
    public: true

  Psr\EventDispatcher\ListenerProviderInterface:
    alias: TYPO3\CMS\Core\EventDispatcher\ListenerProvider
    public: true